### ISSUE TITLE
ValidationError and module not found error on run npm

### ISSUE THREAD

**Issue by abdullaadnan** [getcandy/hub#49] opened 2021-04-06 06:57 UTC
OS: Ubuntu 20.04.2 LTS TYPE:64bit
node: v12.20.2

**Describe the bug**
After I cloning the hub repo and installed npm and when command "npm run dev" it shows an error as
`ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
options.modules has an unknown property 'compileType'. These properties are valid:

**Screenshots**
![Screenshot from 2021-04-05 20-20-17](https://user-images.githubusercontent.com/47655583/113670525-dc677b80-96d2-11eb-97a5-e3366e8822e0.png)

**Comment by alecritson** [comment] 2021-04-06 07:57
Looks like a dupe of #48 

Can you also try using `yarn` instead of `npm`

**Closed by alecritson** 2021-04-06 07:57 UTC

**Comment by abdullaadnan** [comment] 2021-04-06 11:37
Sir, I tried in yarn same error that occurred  when `yarn dev `command 
![Screenshot from 2021-04-06 16-58-23](https://user-images.githubusercontent.com/47655583/113704788-3def1080-96fa-11eb-8766-936d82da4367.png)

**Comment by alecritson** [comment] 2021-04-06 11:41
@abdullaadnan If you check out #48 can you see if the latest comment fixes things for you?

**Comment by abdullaadnan** [comment] 2021-04-06 15:53
thank you sir for your valuable information my error Is fixed
